#%RAML 1.0
title: Mobile User Contact
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile-user-contact:
  /feedback-submissions:
    post:
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      displayName: Submit feedback
      description:
        Submits user feedback about the HMRC mobile app.
        Returns a 2xx response when the feedback submission was successfully added to the queue.
        May be enhanced in future to include a ticket URL or ID in the response.
      body:
        application/json:
          type: !include schemas/feedback-submission.json
          example: !include examples/feedback-submission.json
      responses:
        # we'll return 202 initially but want to be able to change this without breaking compatibility
        200:
        201:
        202:
        204:
  /support-requests:
    post:
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      displayName: Request support
      description:
        Sends a request for support.
        Returns a 2xx response when the feedback was successfully be added to the queue.
        May be enhanced in future to include a ticket URL or ID in the response.
      body:
        application/json:
          type: !include schemas/support-request.json
          example: !include examples/support-request.json
      responses:
        # we'll return 202 initially but want to be able to change this without breaking compatibility
        200:
        201:
        202:
        204:
